spring.application.name=storetrack_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/storetrack_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# # for localdate and time to b HH:mm and not HH:mm:ss:nn
# spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC
